var gameconfig = {
        npcnamecolor: "#FFC627",
        gamename: "West Law",
        aboutme: "BrowserQuest Enhanced with iAppsBeats features.",
        facebookpage: "https://www.facebook.com/browserquest",
        facebookscopes: "public_profile,email",
        forumurl: "https://discord.gg/browserquest",
        privacyurl: "https://browserquest.com/privacy",
        docsurl: "https://docs.browserquest.com",
        adminfilesurl: "https://localhost:5000/admin/files",
        adminconfigurl: "https://localhost:5000/admin/config",
        adminscriptsurl: "https://localhost:5000/admin/scripts",
        adminmapsurl: "https://localhost:5000/admin/maps",

        alwaysgrab: true,
        enablegrab: true,
        primaryweapon: "sword1",
        defaultarmor: "clotharmor",
        defaultweapon: "sword1",
        defaulthead: "bbuilder_head1.png",
        defaulthat: null,
        defaultmapname: "world_client",

        filespath: "./client/files/",
        enablesharebutton: false,
        enablenewgui: false,
        enablebackpackani: true,
        enablefbinvite: false,
        enablehitbox: true,
        enablesleep: true,
        enabletitles: true,
        font: "brothers",
        hotkeys: 5,
        shiftchat: false,
        clearcolor: [0.1568,0.1568,0.1568],
        uploadavailabletypes: ["HEAD", "BODY", "HAT"],
        uploadpricehat:  5000,
        uploadpricehead: 3000,
        uploadpricebody: 3000,
        giftopprice: 500,
        clancreateprice: 500,
        clanrenameprice: 100,
        clanmemberlimit: 24,
        clandisbandbonus: 200,
        minimaparea: {x:270, y:124, w:45, h:45},
        minimapdynamic: true,
        minimapround: false,
        minimaphead: true,
        noplayercount: true,
        noguimaps: ["ban"],
        mapfullwindow: true,
        invitemessage: "Check out BrowserQuest Enhanced!",
        extendedemoticons: true,
        emoticonoffset: {x:-8, y:-75},
        showcoinsarrow: true,
        showfurnitureshops: true,
        idlepose: "player_idlepose1",
        idleposetime: 60,
        randomatk2: true,
        markerpos: {
        },
        searchcategories: ["hat","head","armor","loot","weapon","furniture","weaponskin"],
        ignoremodtimefor: ["_hatc", "_headc", "_bodyc", "_clanlogoc"],

        enablepaypal: false,
        serveraddress: "",

        storyshareurl: "https://localhost:5000/story/share?storyid=",
        twitteraccount: "BrowserQuest",
        twitterhashtags: "browserquest,game",

        cognitoclientid: "",
        cognitoredirecturi: "https://localhost:5000",
        cognitoapidomain: "",

        gameads: [
        ],
        "story": {
            "youtubelink": "<iframe width=400 height=400 allow=autoplay src=https://www.youtube.com/embed/%s?rel=0&autoplay=1 frameborder=0 allowfullscreen=true></iframe>",
            "instagramlink": "<iframe class=\"instagram-media instagram-media-rendered\" id=\"instagram-embed-0\" src=\"https://www.instagram.com/p/%s/embed\" allowtransparency=\"true\" frameborder=\"0\" height=\"400\" data-instgrm-payload-id=\"instagram-media-payload-0\" scrolling=\"no\" style=\"width: 400px;\"></iframe>",
            "twitchlink": "<iframe width=400 height=400 src=https://player.twitch.tv/?%s&parent=localhost&parent=127.0.0.1 frameborder=0 allowfullscreen=true></iframe>",
            "tiktoklink": "<iframe src=https://www.tiktok.com/embed/v2/%s allow=autoplay frameborder=0 allowfullscreen=true style=\"width:100%%;height:100%%;\"></iframe>",
            "facebooklink": "<iframe src=\"https://www.facebook.com/plugins/post.php?href=https://www.facebook.com/%s&show_text=true\" width=400 height=400 style=\"background-color:white;border:none;overflow:hidden\" scrolling=no frameborder=0 allowfullscreen=true allow=\"autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share\"></iframe>"
        }
};