var gameconfig = {
        npcnamecolor: "#FFC627",
        gamename: "West Law",
        aboutme: "West Law is a development game server of iAppsBeats.",
        facebookpage: "https://www.facebook.com/avaloniaonline",
        facebookscopes: "public_profile,email",
        forumurl: "https://discord.gg/Fhx7w3pnvx",
        privacyurl: "https://server1.iappsbeats.com/privacypolicy.htm",
        docsurl: "https://docs.iappsbeats.com",
        adminfilesurl: "https://gitlab.iappsbeats.com/servers/server_1/FilesX",
        adminconfigurl: "https://gitlab.iappsbeats.com/servers/server_1/Config",
        adminscriptsurl: "https://gitlab.iappsbeats.com/servers/server_1/Scripts",
        adminmapsurl: "https://gitlab.iappsbeats.com/servers/server_1/Maps",

        alwaysgrab: true,
        enablegrab: true,
        primaryweapon: "gun",
        defaultarmor: "clotharmor",
        defaultweapon: "sword1",
        defaulthead: "bbuilder_head1.png",
        defaulthat: null,
        defaultmapname: "westlaw_overworld",

        filespath: "https://files.iappsbeats.com/Servers/server_1/Files/",
        enablesharebutton: false,
        enablenewgui: false,
        enablebackpackani: true,
        enablefbinvite: true,
        enablehitbox: true,
        enablesleep: true,
        enabletitles: true,
        font: "brothers",
        hotkeys: 5,
        shiftchat: false,
        clearcolor: [0.1568,0.1568,0.1568],
        uploadavailabletypes: ["HEAD", "BODY", "HAT"],
        uploadpricehat:  5000,
        uploadpricehead: 3000,
        uploadpricebody: 3000,
        giftopprice: 500,
        clancreateprice: 500,
        clanrenameprice: 100,
        clanmemberlimit: 24,
        clandisbandbonus: 200,
        minimaparea: {x:270, y:124, w:45, h:45},
        minimapdynamic: true,
        minimapround: false,
        minimaphead: true,
        noplayercount: true,
        noguimaps: ["ban"],
        mapfullwindow: true,
        invitemessage: "Check out West Law, the new online game!",
        extendedemoticons: true,
        emoticonoffset: {x:-8, y:-75},
        showcoinsarrow: true,
        showfurnitureshops: true,
        idlepose: "player_idlepose1",
        idleposetime: 60,
        randomatk2: true,
        markerpos: {
        },
        searchcategories: ["hat","head","armor","loot","weapon","furniture","weaponskin"],
        ignoremodtimefor: ["_hatc", "_headc", "_bodyc", "_clanlogoc"],

        enablepaypal: false,
        serveraddress: "d3NzOi8vaWFwcHNiZWF0cy5jb20vc2VydmVyMXdzcw==",

        storyshareurl: "https://iappsbeats.com/bbuilder/facebook/storyvideo.php?storyid=",
        twitteraccount: "Avalonia_Online",
        twitterhashtags: "iappsbeats,avaloniaonline",

        cognitoclientid: "33daef2s3v0asak5vcur92mfmp",
        cognitoredirecturi: "https://server1.iappsbeats.com",
        cognitoapidomain: "auth.avaloniaonline.com",

        gameads: [
        ],
        "story": {
            "youtubelink": "<iframe width=400 height=400 allow=autoplay src=https://www.youtube.com/embed/%s?rel=0&autoplay=1 frameborder=0 allowfullscreen=true></iframe>",
            "instagramlink": "<iframe class=\"instagram-media instagram-media-rendered\" id=\"instagram-embed-0\" src=\"https://www.instagram.com/p/%s/embed\" allowtransparency=\"true\" frameborder=\"0\" height=\"400\" data-instgrm-payload-id=\"instagram-media-payload-0\" scrolling=\"no\" style=\"width: 400px;\"></iframe>",
            "twitchlink": "<iframe width=400 height=400 src=https://player.twitch.tv/?%s&parent=iappsbeats.com&parent=avaloniaonline.com&parent=corleoneonline.com frameborder=0 allowfullscreen=true></iframe>",
            "tiktoklink": "<iframe src=https://www.tiktok.com/embed/v2/%s allow=autoplay frameborder=0 allowfullscreen=true style=\"width:100%%;height:100%%;\"></iframe>",
            "facebooklink": "<iframe src=\"https://www.facebook.com/plugins/post.php?href=https://www.facebook.com/%s&show_text=true\" width=400 height=400 style=\"background-color:white;border:none;overflow:hidden\" scrolling=no frameborder=0 allowfullscreen=true allow=\"autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share\"></iframe>"
        }
};
